# Generated by Django 5.1.7 on 2025-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
