# Generated by Django 5.1.7 on 2025-04-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0002_alter_vendors_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=255)),
                ('category_url', models.URLField(max_length=255)),
                ('category_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('pricing', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.category')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_name', models.CharField(max_length=255, unique=True)),
                ('menu_url', models.URLField(max_length=255)),
                ('image_field', models.ImageField(upload_to='images/')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.menu'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('total_price', models.IntegerField()),
                ('order_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tableapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('qr_code_url', models.URLField(max_length=255)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.menu')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.tables'),
        ),
    ]
