# Generated by Django 5.1.7 on 2025-04-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_cart_category_item_category_item_cart_item_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.CharField(max_length=255),
        ),
    ]
