# Generated by Django 5.1.7 on 2025-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_alter_menu_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_url',
            field=models.CharField(max_length=255),
        ),
    ]
