# Generated by Django 5.1.7 on 2025-04-14 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0006_alter_category_category_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='username',
        ),
        migrations.AddField(
            model_name='vendors',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
