# Generated by Django 5.1.7 on 2025-04-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0007_remove_vendors_email_remove_vendors_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
