# Generated by Django 5.1.7 on 2025-04-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0008_alter_vendors_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='mobile_no',
        ),
    ]
