# Generated by Django 5.1.7 on 2025-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0009_remove_vendors_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pricing',
            field=models.FloatField(),
        ),
    ]
