# Generated by Django 5.1.7 on 2025-04-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0010_alter_item_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category_item',
            old_name='item_id',
            new_name='item',
        ),
    ]
