# Generated by Django 5.1.7 on 2025-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0011_rename_category_id_category_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
