# Generated by Django 5.1.7 on 2025-04-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0013_cart_is_active_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
