# Generated by Django 5.1.7 on 2025-05-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0015_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_name',
        ),
    ]
